### ISSUE TITLE
Primary and Replicated/EC PG's show syntax error

### ISSUE THREAD

**Issue by xakaitetoia** [JoshSalomon/Cephalocon-2019#2]
Tried to run the script and in the end i get 
# PRIMARY and Replicated/EC PGs number per OSD sorted by total descending:
awk: line 1: syntax error at or near [
awk: line 3: syntax error at or near [
awk: line 3: syntax error at or near [
awk: line 5: syntax error at or near [
awk: line 5: syntax error at or near [

Anything i am missing?

**Comment by JoshSalomon** [comment]
What is your environment (OS and awk version)?

**Comment by JoshSalomon** [comment]
Please also send me the shell and shell version you are using.

**Comment by xakaitetoia** [comment]
OS

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"


awk -W version 
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040

shell version


GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by JoshSalomon** [comment]
Hi, it seems your awk version is very old - please upgrade to GNU Awk version 4.2 or later, it should work with it (probably with older 4.x versions as well)

**Comment by xakaitetoia** [comment]
Ah thanks a lot.. that was it.. Appreciate your quick response..
